apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    tier: DB
    app: mongodb
    project: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: DB
      app: mongodb
      project: Roboshop
  template:
    metadata:
      labels:
        tier: DB
        app: mongodb
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:1.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    tier: DB
    app: mongodb
    project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017