apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    tier: DB
    app: mysql
    project: roboshop
spec:
  replicas: 2
  selector:
     matchLabels:
      tier: DB
      app: mysql
      project: roboshop
  template:
    metadata:
      labels:
        tier: DB
        app: mysql
        project: roboshop
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:1.0.0
        envFrom:
        - configMapRef:
            name: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    tier: DB
    app: mysql
    project: roboshop
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # keep true in double quotes
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "RoboShop@1"

