apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    tier: DB
    app: redis
    project: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: DB
      app: redis
      project: roboshop
  template:
    metadata:
      labels:
        tier: DB
        app: redis
        project: roboshop
    spec:
      containers:
      - name: redis
        image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    tier: DB
    app: redis
    project: roboshop
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379