apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    tier: app
    app: shipping
    project: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: app
      app: shipping
      project: roboshop
  template:
    metadata:
      labels:
        tier: app
        app: shipping
        project: roboshop
    spec:
      containers:
      - name: shipping
        image: joindevops/shipping:1.0.0
        envFrom:
        - configMapRef:
            name: shipping

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    tier: app
    app: shipping
    project: roboshop
  ports:
  - name: shipping-port
    protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"