apiVersion: apps/v1
kind: Statefulset
metadata:
  name: mongodb
  labels:
    tier: DB
    app: mongodb
    project: roboshop
spec:
  serviceName: mongodb
  replicas: 2
  selector:
    matchLabels:
      tier: DB
      app: mongodb
      project: roboshop
  template:
    metadata:
      labels:
        tier: DB
        app: mongodb
        project: roboshop
    spec:
      containers:
        - name: mongodb
          image: joindevops/mongodb:1.0.0
          volumeMounts:
          - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: None
  selector:
    tier: DB
    app: mongodb
    project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017

    
  


  