apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    tier: DB
    project: roboshop
    app: mysql
spec:
  serviceName: mysql
  replicas: 2
  selector:
    matchLabels:
      tier: DB
      project: roboshop
      app: mysql
  template:
    metadata:
      labels:
        tier: DB
        project: roboshop
        app: mysql
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:1.0.0
        volumeMounts:
        - name: mysql
          mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-dynamic-ebs"
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1 
kind: Service
metadata:
  name: mysql
spec:
  selector:
    tier: DB
    project: roboshop
    app: mysql
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306