apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: roboshop
data:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: nginx
        access:
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          var.paths: ["/var/log/nginx/error.log*"]
    output:
      elasticsearch:
        hosts: ["elasticsearch:9200"]

---
apiVersion: v1
kind: Deployment
metadata:
  name: nginx
  namespace: roboshop
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
  spec:
    containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
      - name: nginx-logs
        mountPath: var/log/nginx/
    - name: filebeat
      image: docker.elastic.co/beats/filebeat:7.5.0
      volemeMounts:
      - name: nginx-logs
        mountPath: var/log/nginx/
      - name: filebeat-config-volume
        mountPath: /usr/share/filebeat/filebeat.yml
        subPath: filebeat.yml 
    volumes:
    - name: nginx-logs
      emptyDir: {}
    - name: filebeat-config-volume
      ConfigMap:
        name: filebeat-config
        items:
          - key: filebeat.yml
            path: filebeat.yml
    

