apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi  # Adjust size as needed
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-00c7233afebe84113
    fsType: ext4  # Filesystem type (optional, defaults to ext4)
